name: microservice-app
services:
  auth-nginx:
    image: nginx:1.28
    container_name: auth-nginx
    ports:
      - "${NGINX_PORT:-80}:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth-keycloak

  auth-keycloak:
    image: quay.io/keycloak/keycloak:26.0
    container_name: auth-keycloak
    command: ["start-dev", "--import-realm"]
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-admin}
      KC_DB: ${KC_DB:-postgres}
#      KC_DB_URL: ${KC_DB_URL:-jdbc:postgresql://auth-postgresql:5432/${KC_DB:-postgres}}
      KC_DB_USERNAME: ${KC_DB_USERNAME:-postgres}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD:-password}
      KC_HOSTNAME: ${KEYCLOAK_HOSTNAME:-localhost}
      KC_HOSTNAME_PORT: ${KEYCLOAK_HOSTNAME_PORT:-80}
      KC_HOSTNAME_STRICT: ${KEYCLOAK_HOSTNAME_STRICT:-false}
      KC_HTTP_ENABLED: ${KEYCLOAK_HTTP_ENABLED:-true}
      KC_PROXY: ${KEYCLOAK_PROXY:-edge}
      KC_PROXY_ADDRESS_FORWARDING: true
    # ports:
    #   - "${KEYCLOAK_PORT:-8080}:8080"
    volumes:
      - ./realm.json:/opt/keycloak/data/import/realm.json:ro
      - ./keycloak-exports:/opt/keycloak/exports
    env_file:
      - .env.auth
    depends_on:
      - auth-postgresql

  auth-postgresql:
    build:
      context: docker/postgresql
      dockerfile: Dockerfile.dev
    container_name: auth-postgresql
    environment:
      POSTGRES_DB: ${KC_DB:-postgres}
      POSTGRES_USER: ${KC_DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${KC_DB_PASSWORD:-password}
    env_file:
      - .env.auth
    ports:
      - "${KC_POSTGRES_PORT:-5432}:5432"
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data
      - ./docker/postgresql/postgresql.conf:/etc/postgresql/postgresql.conf

  auth-mailhog:
    container_name: auth-mailhog
    image: mailhog/mailhog
    ports:
      - "${MAIL_UI_PORT:-8025}:8025"
      - "${MAIL_SMTP_PORT:-1025}:1025"
    env_file:
      - .env
    volumes:
      - auth_mailhog_data:/home/mailhog

#  auth-kc-tools:
#    build:
#      context: .
#      dockerfile: docker/tool/Dockerfile.dev
#    container_name: keycloak-tools
#    command: [ "sleep", "infinity" ]
#    user: "${UID}:${GID}"
#    depends_on:
#      - auth-keycloak
#    volumes:
#      - ./keycloak-exports:/opt/keycloak/exports
#    environment:
#      KEYCLOAK_URL: "http://auth-keycloak:8080"

volumes:
  auth_postgres_data:
  auth_mailhog_data:
